### ISSUE TITLE
[FlixPatrol Assets]: Migrate some of the key aspects of PMM

### ISSUE THREAD

**Issue by alejakun** [Navino16/flixpatrol-top10-on-trakt#17]
### Describe the feature

The current link to FlixPatrol Assets in PMM are:

Overlay Badges (colored backgound): `https://github.com/meisnate12/Plex-Meta-Manager/tree/master/defaults/overlays/images/logo`
Overlay Logos (company logos): `https://github.com/meisnate12/Plex-Meta-Manager-Images/tree/master/chart/overlays`
Collection TOP 10 posters: `https://github.com/meisnate12/Plex-Meta-Manager-Images/tree/master/chart`

apple_top.jpg
disney_top.jpg
google_top.jpg
hbo_top.jpg
hulu_top.jpg
imdb_top.jpg
itunes_top.jpg
max_top.jpg
netflix_top.jpg
paramount_top.jpg
prime_top.jpg
star_top.jpg
vudu_top.jpg

**Comment by Navino16** [comment]
Overlays logo are here:
https://github.com/Navino16/flixpatrol-top10-on-trakt/tree/main/assets/overlays/logo

The other images shouldn't be removed from PMM so they aren't added to this repository
