### ISSUE TITLE
[SUPPORT]: Schedule run time 

### ISSUE THREAD

**Issue by Schnoopie-Doopie** [Navino16/flixpatrol-top10-on-trakt#64]
### Version Number

main\:latest

### What branch are you on?

main

### Describe the issue

I have tested this great app on Windows and have since moved it into docker on my NAS however, I cant figure out how to schedule it to run at a certain time. Is there a variable I can set to run this at say 3am every day?

### Relevant configuration

```json
The config works fine in docker, just a scheduling question
```

**Comment by Navino16** [comment]
@Schnoopie-Doopie use a cron job (https://en.wikipedia.org/wiki/Cron) to do that.
Here is mine:
```
0 2 * * * docker run --rm -e TZ=Europe/Paris -v "/my/path/to/flixpatrol-top10/config/:/app/config" ghcr.io/navino16/flixpatrol-top10-on-trakt:latest
```
